# Generated by Django 6.0.4 on 2026-04-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_internshipagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='internship_privacy',
            field=models.CharField(choices=[('public', 'Public — everyone can see'), ('private', 'Private — only me'), ('selected', 'Selected — I choose which ones')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
