# Generated by Django 6.0.4 on 2026-05-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_skill_student_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(choices=[('1', '1st Year (L1)'), ('2', '2nd Year (L2)'), ('3', '3rd Year (L3)'), ('4', '4th Year (M1)'), ('5', '5th Year (M2)'), ('D', 'Doctorate')], default='3', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
