# Generated by Django 3.2.25 on 2026-05-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20260502_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.internshipoffer'),
        ),
        migrations.AlterUniqueTogether(
            name='internship',
            unique_together={('student', 'offer')},
        ),
    ]
