# Generated by Django 3.2.25 on 2026-05-05 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20260502_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_accepted', 'Application Accepted by Company'), ('application_rejected', 'Application Rejected by Company'), ('internship_validated', 'Internship Validated by Admin'), ('new_applicant', 'New Student Applied'), ('agreement_ready', 'Agreement Ready'), ('admin_rejected', 'Internship Rejected by Admin'), ('internship_accepted', 'Internship Accepted by Company')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
