# Generated by Django 6.0.4 on 2026-05-06 16:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_internshipoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.offer_image_file_path),
        ),
    ]
