# Generated by Django 3.2.25 on 2026-05-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20260505_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('year_1', 'Year 1 (License 1)'), ('year_2', 'Year 2 (License 2)'), ('year_3', 'Year 3 (License 3)'), ('year_4', 'Year 4 (Master 1)'), ('year_5', 'Year 5 (Master 2)'), ('doctorate', 'Doctorate')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='professional_summary',
            field=models.TextField(blank=True, help_text='Short professional summary for the Digital CV.'),
        ),
    ]
