# Generated by Django 6.0.4 on 2026-05-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_internshipoffer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='type',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
    ]
