# Generated by Django 6.0.4 on 2026-05-08 14:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_company_industry_company_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.internshipoffer'),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='duration_months',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='internship',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('internship_validated', 'Internship Validated by University'), ('internship_rejected', 'Internship Rejected by University'), ('agreement_ready', 'Convention de Stage Ready')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notifications', to='core.internship')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notifications', to='core.student')),
            ],
            options={
                'verbose_name': 'Student Notification',
                'verbose_name_plural': 'Student Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
