# Generated by Django 6.0.4 on 2026-05-09 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_internship_offer_internshipoffer_duration_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_application', 'New Internship Application'), ('application_validated', 'Internship Validated by Admin'), ('application_rejected', 'Internship Rejected by Admin')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_notifications', to='core.internship')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_notifications', to='core.company')),
            ],
            options={
                'verbose_name': 'Company Notification',
                'verbose_name_plural': 'Company Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
