# Generated by Django 6.0.4 on 2026-05-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_companynotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipoffer',
            name='duration_months',
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
