"""URL mappings for the administration API."""
from django.urls import path

from administration import views

app_name = 'administration'

urlpatterns = [
    # Admin Reset Data
    path(
        'reset-data/',
        views.AdminResetDataView.as_view(),
        name='admin-reset',
    ),
    # Notifications
    path(
        'notifications/',
        views.NotificationListView.as_view(),
        name='notification-list',
    ),
    path(
        'notifications/unread/',
        views.UnreadNotificationListView.as_view(),
        name='notification-unread',
    ),
    path(
        'notifications/<int:pk>/read/',
        views.MarkNotificationReadView.as_view(),
        name='notification-read',
    ),
    path(
        'notifications/mark-all-read/',
        views.MarkAllNotificationsReadView.as_view(),
        name='notification-mark-all-read',
    ),
    # Internships
    path(
        'internships/',
        views.AllInternshipListView.as_view(),
        name='internship-list',
    ),
    path(
        'internships/<int:pk>/',
        views.InternshipDetailView.as_view(),
        name='internship-detail',
    ),
    path(
        'internships/<int:pk>/agreement/',
        views.DownloadInternshipAgreementView.as_view(),
        name='internship-agreement-download',
    ),
    path(
        'internships/<int:pk>/validate/',
        views.ValidateInternshipView.as_view(),
        name='internship-validate',
    ),
    path(
        'internships/<int:pk>/reject/',
        views.RejectInternshipView.as_view(),
        name='internship-reject',
    ),
    # Statistics
    path(
        'statistics/',
        views.StatisticsSummaryView.as_view(),
        name='statistics-summary',
    ),
    path(
        'statistics/companies/',
        views.StatisticsCompaniesView.as_view(),
        name='statistics-companies',
    ),
    path(
        'statistics/wilayas/',
        views.StatisticsWilayasView.as_view(),
        name='statistics-wilayas',
    ),
    path(
        'statistics/trends/',
        views.StatisticsTrendsView.as_view(),
        name='statistics-trends',
    ),
    path(
        'statistics/agreements/',
        views.StatisticsAgreementsView.as_view(),
        name='statistics-agreements',
    ),
    path(
        'statistics/statuses/',
        views.StatisticsStatusesView.as_view(),
        name='statistics-statuses',
    ),
    path(
        'statistics/trends/',
        views.StatisticsTrendsView.as_view(),
        name='statistics-trends',
    ),
    path(
        'statistics/students/',
        views.StatisticsStudentsView.as_view(),
        name='statistics-students',
    ),
    path(
        'statistics/companies/<int:company_id>/',
        views.StatisticsCompanyDetailView.as_view(),
        name='statistics-company-detail',
    ),
    path(
        'statistics/at-risk/',
        views.StatisticsAtRiskView.as_view(),
        name='statistics-at-risk',
    ),
    # Student Actions
    path(
        'student/apply/',
        views.StudentInternshipListCreateView.as_view(),
        name='student-internship-list-create',
    ),
    # Company Actions
    path(
        'company/internships/',
        views.CompanyInternshipListView.as_view(),
        name='company-internship-list',
    ),
    path(
        'company/internships/<int:pk>/accept/',
        views.CompanyAcceptInternshipView.as_view(),
        name='company-internship-accept',
    ),
    path(
        'company/internships/<int:pk>/reject/',
        views.CompanyRejectInternshipView.as_view(),
        name='company-internship-reject',
    ),
    # Company Offers
    path(
        'company/offers/',
        views.CompanyInternshipOfferListCreateView.as_view(),
        name='company-offer-list',
    ),
    path(
        'company/offers/<int:pk>/',
        views.CompanyInternshipOfferDetailView.as_view(),
        name='company-offer-detail',
    ),
    path(
        'company/offers/<int:pk>/upload-image/',
        views.CompanyOfferImageUploadView.as_view(),
        name='company-offer-image-upload',
    ),
    # Public
    path(
        'public/companies/',
        views.PublicCompanyListView.as_view(),
        name='public-company-list',
    ),
    path(
        'public/offers/',
        views.PublicInternshipOfferListView.as_view(),
        name='public-offer-list',
    ),
    path(
        'public/offers/<int:pk>/',
        views.PublicInternshipOfferDetailView.as_view(),
        name='public-offer-detail',
    ),
    # Company Stats
    path(
        'company/stats/',
        views.CompanyDashboardStatsView.as_view(),
        name='company-dashboard-stats',
    ),
    path(
        'company/offers/<int:pk>/stats/',
        views.CompanyOfferStatsView.as_view(),
        name='company-offer-stats',
    ),
    # Company Notifications
    path(
        'company/notifications/',
        views.CompanyNotificationListView.as_view(),
        name='company-notification-list',
    ),
    path(
        'company/notifications/mark-read/',
        views.MarkCompanyNotificationsReadView.as_view(),
        name='company-notification-mark-read',
    ),
    # Student Notifications
    path(
        'student/notifications/',
        views.StudentNotificationListView.as_view(),
        name='student-notification-list',
    ),
    path(
        'student/notifications/<int:pk>/read/',
        views.StudentMarkNotificationReadView.as_view(),
        name='student-notification-read',
    ),
    path(
        'student/agreements/<int:pk>/download/',
        views.StudentDownloadAgreementView.as_view(),
        name='student-agreement-download',
    ),
    path(
        'notifications/mark-all-read/',
        views.MarkAllNotificationsReadView.as_view(),
        name='notification-mark-all-read',
    ),
]
