# Generated by Django 3.2.25 on 2026-05-02 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('core', '0007_internshipoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='OfferSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_skills', to='core.internshipoffer')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_skills', to='student.skill')),
            ],
            options={
                'unique_together': {('offer', 'skill')},
            },
        ),
    ]
